name: Sandbox
description: Sandbox execution within nestable user namespaces
author: https://github.com/staticfloat
configuration:
  properties:
    # This defines the rootfs we will be launching inside of; users must provide both the URL and the treehash
    rootfs_url:
      type: string
    rootfs_treehash:
      type: string

    # Allow mounting arbitrary read-write directories; specified as `host:sandbox`
    # Note that the sandbox automatically gets access to:
    # - `${BUILDKITE_BUILD_PATH}`: the repository checkout path
    # - `${BUILDKITE_PLUGINS_PATH}`: the plugins directory
    # - `${TMPDIR}`: the temporary directory, since many plugins require communicating through it
    # - `buildkite-agent`: wherever `buildkite-agent` is located, it gets mapped in as `/usr/bin/buildkite-agent`.
    # - `/etc/resolv.conf`: We assume you want to be able to resolve DNS queries.
    workspaces:
      type: array

    # Allow setting the UID and GID of the sandbox user (defaults to the current user)
    uid:
      type: string
    gid:
      type: string

    # If this is set, causes all sorts of debugging information to be printed out
    verbose:
      type: boolean
    
  additionalProperties: false
