name: Sandbox
description: Sandbox execution within nestable user namespaces
author: https://github.com/staticfloat
configuration:
  properties:
    # This defines the rootfs we will be launching inside of; users must provide both the URL and the treehash
    rootfs_url:
      type: string
    rootfs_treehash:
      type: string

    # Allow mounting arbitrary read-write directories; specified as `host:sandbox`
    workspaces:
      type: array

    # Allow setting the UID and GID of the sandbox user (defaults to the current user)
    uid:
      type: string
    gid:
      type: string
    
  additionalProperties: false
